### ISSUE TITLE
Internal App - Design - Develop V1 Design

### ISSUE THREAD

**Issue by cedricwaxwing** [dOrgTech/app-dorg#16]

**Comment by cedricwaxwing** [comment]
@carlosfebres @dorglkramer
I've created a new v1 Page in the dOrg App file. Inside are 5 frames:

- Sign In Page
- Projects Page
- Create a New Project
- Project Page - Proposal State
- Project Page - Active

I've left comments inline on the document for more clarity, but there will be some UX that we will still need to refine (ex: What to display on active project "budget")

https://www.figma.com/file/gdaD0XaSG4sw046Vl88oJ7/dOrg-App?node-id=11%3A77

**Comment by dOrgJelli** [comment]
This looks phenomenal! I wish I had more feedback, but nothing comes to mind, great work all :clap: :clap: :rocket:

**Comment by carlosfebres** [comment]
Great job @cedricwaxwing!! Looks amazing 🚀 
I'm going to start working with this, I'll try to have something to show for our Wednesday sync
